# Generated by Django 4.1.3 on 2022-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='pub_date')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
